config/routes.rb
Rails.application.routes.draw do


  resources :academic_fees, except: %i[create new show destroy] do
    collection do
      get :find_academic_sections
      get :find_students
      get :find_student_details
      post :filter
      get :pay_fee
      get :changed_fee
    end
    member do
      post :create_payment
    end
  end

  resources :fee_dues, except: %i[create new edit update show destroy] do
    collection do
      get :find_academic_sections
      post :filter_fee_due
    end
  end

  resources :payments, except: %i[create new edit update show destroy]   do
    member do
      get :invoice
    end
  end


  namespace :staff do
    resources :notices, only: %i[index]
    resources :attendances, only: %i[index]
  end

  devise_for :users
  root 'home#index'

  resources :academic_details, except: %i[create new show]

  resources :schools, except: %i[index show destroy]

  resources :notices, except: %i[new show edit update]

  resources :students, except: %i[show] do
    collection do
      get :find_sections
      get :find_from_sections
      get :find_to_sections
      get 'promote'
      post 'update_sections'
    end
    member do
      patch :active_student
    end
  end

  namespace :parent do
    resources :attendance_views, only: %i[index]
    resources :notices, only: %i[index]
  end

  resources :user_attendances, except: %i[show edit update destroy create] do
    collection do
      post :update_all
    end
  end

  resources :student_attendances, except: %i[show new edit update destroy create] do
    collection do
      post :update_all
      get :attendance_view
    end
    collection do
      get :find_sections
    end
  end

  resources :standards, except: %i[show new] do
    resources :sections, only: []
  end

  namespace :admin do
    resources :admin_users, only: %i[edit update] do
    end
  end

  namespace :admin do
    resources :parent_users, except: [:show] do
      collection do
        get :check_username
      end
      member do
        patch :active_user
      end
    end
  end
  namespace :admin do
    resources :staff_users do
      member do
        patch :active_staff_user
      end
    end
  end
end

app/controllers/admin/staff_users_controller.rb
# frozen_string_literal: true

# Controller responsible for managing staff users in the admin section.
# This controller includes actions for listing, creating, updating, and deleting staff users.
class Admin::StaffUsersController < ApplicationController
  include AuthorizationHelper
  before_action :check_admin_role
  before_action :set_user, only: %i[edit update destroy active_staff_user]
  include UserToggle
  def index
    @staffs = User.where(role: 'staff')
    respond_to do |format|
      format.html
      format.json { render json: StaffUserDatatable.new(params) }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = build_new_user
    @user.role = 'staff'
    if @user.save
      flash[:notice] = 'User created successfully.'
      redirect_to admin_staff_users_path
    else
      flash[:alert] = 'Failed to create user.'
      render :new
    end
  end

  def active_staff_user
    toggle_user_status(@user)
    redirect_to admin_staff_users_path
  end

  def edit
    return if @user.present?

    flash[:alert] = 'User not found.'
    redirect_to admin_staff_users_path
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User information updated successfully.'
      redirect_to admin_staff_users_path
    else
      flash[:alert] = 'Failed to update user information.'
      render :edit
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = 'admin cannot delete self.'
    elsif @user.update(removed: true)
      flash[:notice] = 'User deleted successfully.'
    else
      flash[:alert] = 'Failed to delete user.'
    end
    redirect_to admin_staff_users_path
  end

  def show; end

  private

  def build_new_user
    User.new(params.require(:user).permit(:email, :password, :username, :mobile_number,
                                          :address, :profession, :gender, :name, :image, :deleted))
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, :mobile_number,
                                 :address, :profession, :gender, :name, :image, :deleted)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/admin/staff_users_helper.rb
module Admin::StaffUsersHelper
end

app/views/admin/staff_users/edit.html.erb
<%= content_for :head do %>
  <%= javascript_import_module_tag "controllers/edit_user" %>
<% end %>
<div class="container bg-[#F5F5F5] mx-auto md:mt-[35px] text-[14px] lg:mt-0 mb-8 p-1.5 rounded-[5px] text-[#2FA4E7] pl-4"><span class="hover:text-[#157AB5]  hover:underline "><%= link_to "Home", root_path %></span><span class="mx-2 text-[#aba7a7]">/</span><span class="hover:text-[#157AB5]  hover:underline pointer"><%= link_to " Manage Staff", admin_staff_users_path %></span><span class="mx-2 text-[#aba7a7]">/</span><span class="hover:text-[#157AB5]  hover:underline pointer"><%= link_to "Edit Staff", edit_admin_staff_user_path(@user)  %></span></div>
<div class=" container mx-auto rounded-[5px] border-2">
  <div class="px-5 bg-[#EDEDED] flex items-center justify-between text-[#317EAC] shadow-2xl", style="background: linear-gradient(rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0.1) 100%);">
    <div><i class="fa-solid fa-pen-to-square"></i>
      <span class="font-[700] text-[15px]">Edit Staff</span></div>
    <button id="updown" class="accordian-header cursor-pointer duration-700 text-2xl leading-0 px-1 my-1  border bg-white text-black font-extrabold h-[26px] rounded-[12px]"> <i class="bx bx-chevron-up"></i></button>
  </div>
  <div class="accordian-body">
    <div class=" hidden text-[#b94a48]  m-4 text-[14px]  rounded bg-[#F2DEDE] " id="error-div">
      <ul class="p-4 pl-[30px]">
        <li class="error" id="email-error"></li>
        <li class="error" id="name-error"></li>
        <li class="error" id="username-error"></li>
        <li class="error" id="password-error"></li>
        <li class="error" id="mobile-number-error"></li>
        <li class="error" id="address-error"></li>
        <li class="error" id="profession-error"></li>
      </ul>
    </div>
    <%= form_for [:admin_staff, @user], html: { id: 'user-form' } do |f| %>
      <%= f.hidden_field :role, value: "staff"%>
      <div class="w-full md:ml-0 lg:ml-[60px] xl:ml-[100px] 2xl:ml-[130px] md:w-[45%] lg:w-[22%] hidden">
        <label for="password" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Password</label>
        <%= f.text_field :encrypted_password, disabled: true, id: "user_password" , class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Password" %>
      </div>
      <div class="px-5  py-2 grid grid-cols-1 md:grid-cols-4">
        <div class="col-span-3">
          <div class="grid grid-cols-1 md:grid-cols-4 gap-y-3 md:gap-x-6 lg:gap-x-7">
            <div class="col-span-1 md:col-span-2">
              <label for="name" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Name</label>
              <%= f.text_field :name, id:"name" ,class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,placeholder:"Name"%>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="email" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Email</label>
              <%= f.email_field :email, id: "user_email", class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "email" %>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="mobile-number" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Mobile No</label>
              <%= f.text_field :mobile_number, id: "mobile-number", class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Mobie" %>
            </div>
            <div class="col-span-1 md:col-span-2">
              <label for="address" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Address</label>
              <%= f.text_field :address, id: "address", class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Address" %>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="profession" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Profession</label>
              <%= f.text_field :profession, id: "profession", class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Profession"  %>
            </div>
            <div class="col-span-1 md:col-span-2">
              <div class="flex flex-wrap md:flex-nowrap lg:gap-6 md:gap-5">
                <div class="w-full md:w-[60%] lg-w-[70%]">
                  <label for="user_name" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Username</label>
                  <%= f.text_field :username, id:"user_name", class:"border bg-[#EDEDED]  border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2 cursor-not-allowed", placeholder:"Username" , readonly: true %>
                </div>
                <div class="w-full md:w-[40%] lg:w-[30%]">
                  <div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="password" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Password</label>
              <%= f.text_field :password, disabled: true, id: "user_password" , class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Password", value: "*******" %>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="gender" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Gender</label>
              <div class="flex" id="gender-radio-group">
                <div class="flex items-center mr-4">
                  <%= f.radio_button :gender, 'male', class:"w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500" %>
                  <label for="inline-radio" class="ml-2 text-sm font-semibold text-[#555555] dark:text-gray-300">Male</label>
                </div>
                <div class="flex items-center mr-4">
                  <%= f.radio_button :gender, 'female', class:"w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500" %>
                  <label for="inline-2-radio" class="ml-2 text-sm font-semibold text-[#555555] dark:text-gray-300">Female</label>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-span-1">
          <div class="pl-5 pt-4">
            <div id="previewSingle"></div>
            <div id="defaultUpload">
              <% if @user.image.attached? %>
                <div class="w-[130px] h-[130px]"><%= image_tag @user.image %></div>
              <% else %>
                <div class="w-[130px] h-[130px]"><img src="<%= asset_path('user.png') %>" alt="Image Description"  ></div>
              <% end %>            </div>
            <div class="file-input-wrapper mt-2">
              <label for="single_file" class=" px-10 py-1.5 bg-white text-[14px]   border-2 rounded-[4px] focus:border-[#66afe9] focus:ring-blue-200">
                <span class=" text-[#555555] font-thin ">Browse</span>
                <%= f.file_field :image, class: "hidden", id: "single_file", accept: "image/*" %>
              </label>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit "Update Teacher",class: 'ml-6 md:ml-4  mb-4 md:ml-5 text-white border border-[1px] border-[#2fa4e7] hover:border-[1px] hover:border-[#1684c2] bg-[#81B944] focus:ring-2 hover:ring-[#000] focus:outline-[#000] focus:ring-[#000] rounded-[4px] text-[14px] text-sm w-auto sm:w-auto px-3 py-2 text-center', style: 'background-image: linear-gradient(#54b4eb, #2fa4e7 60%, #1d9ce5);'%>
    <% end %>
  </div>
</div>

app/views/admin/staff_users/index.html.erb
<%= content_for :head do %>
  <%= javascript_import_module_tag "controllers/staff_datatable" %>
<% end %>
<div class="container bg-[#F5F5F5] mx-auto md:mt-[35px] text-[14px] lg:mt-0 mb-8 p-1.5 rounded-[5px] text-[#2FA4E7] pl-4"><span class="hover:text-[#157AB5]  hover:underline "><%= link_to "Home", root_path %></span><span class="mx-2 text-[#aba7a7]">/</span><span class="hover:text-[#157AB5]  hover:underline pointer"><%= link_to " Manage Staff", admin_staff_users_path %></span></div>
<div class=" container mx-auto rounded-lg border-2">
  <div class=" px-5 bg-[#EDEDED] flex items-center justify-between text-[#317EAC] shadow-2xl",, style="background: linear-gradient(rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0.1) 100%);">
    <div><i class="fa-solid fa-pen-to-square"></i>
      <span class="font-[700] text-[15px]">Manage Staff</span></div>
    <button id="updown" class="accordian-header cursor-pointer duration-700 text-2xl leading-0 px-1 my-1  border bg-white text-black font-extrabold h-[26px] rounded-[12px]"> <i class="bx bx-chevron-up"></i></button>
  </div>
  <div class="accordian-body">
    <div class="bg-[#FFFFFF] mx-[8px] md:mx-2 lg:mx-3 xl:mx-0">
      <% if notice %>
        <div class="ml-2">
          <p id="notice"  class="alert text-[#508C47] conatiner text-left text-[14px] rounded bg-[#DFF0D8] mt-2 mr-3 p-3 mb-3"><%= notice %></p>
        </div>
      <% end %>
      <table id="staffTable" class="stripe"  data-source="<%= admin_staff_users_path(format: :json) %>">
        <thead class="bg-[#FFFFFF]">
          <tr>
            <th >Name</th>
            <th>Username</th>
            <th >Email</th>
            <th >Mobile</th>
            <th >Address</th>
            <th >profession</th>
            <th >Gender</th>
            <th >Status</th>
            <th >Action</th>
          </tr>
        </thead>
        <tbody class="bg-[#F9F9F9] ">
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/staff_users/new.html.erb
<%= content_for :head do %>
  <%= javascript_import_module_tag "controllers/validate" %>
<% end %>
<div class=" bg-[#F5F5F5] p-1.5 container mx-auto md:mt-[35px] text-[14px] lg:mt-0 mb-8 text-[#2FA4E7] pl-4"><span class="hover:text-[#157AB5]  hover:underline "><%= link_to "Home", root_path %></span><span class="mx-2 text-[#aba7a7]">/</span><span class="hover:text-[#157AB5]  hover:underline pointer"><%= link_to "Add Staff", new_admin_staff_user_path %></span></div>
<div class=" container mx-auto rounded-[5px] border-2">
  <div class="px-5 bg-[#EDEDED] flex items-center justify-between text-[#317EAC] shadow-2xl",, style="background: linear-gradient(rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0.1) 100%);">
    <div><i class="fa-solid fa-pen-to-square"></i>
      <span class="font-[700] text-[15px]">Add Staff</span></div>
    <button id="updown" class="accordian-header cursor-pointer duration-700 text-2xl leading-0 px-1 my-1  border bg-white text-black font-extrabold h-[26px] rounded-[12px]"> <i class="bx bx-chevron-up"></i></button>
  </div>
  <div class="accordian-body">
    <div class=" hidden text-[#b94a48]  m-4 text-[14px]  rounded bg-[#F2DEDE] " id="error-div">
      <ul class="p-4 pl-[30px]">
        <li class="error" id="email-error" ></li>
        <li class="error" id="name-error" ></li>
        <li class="error" id="username-error" ></li>
        <li class="error" id="password-error" ></li>
        <li class="error" id="mobile-number-error" ></li>
        <li class="error" id="address-error" ></li>
        <li class="error" id="profession-error" ></li>
        <li class="error" id="username-available-error"></li>
      </ul>
    </div>
    <%= form_for @user, url: admin_staff_users_path, method: :post, html: { id: 'user-form' } do |f| %>
      <%= f.hidden_field :role, value: "staff"%>
      <div class="px-5  py-2 grid grid-cols-1 md:grid-cols-4  ">
        <div class="col-span-3">
          <div class="grid grid-cols-1 md:grid-cols-4 gap-y-3 md:gap-6 lg:gap-x-7">
            <div class="col-span-1 md:col-span-2">
              <label for="name" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Name</label>
              <%= f.text_field :name, id:"name" ,class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,placeholder:"Name"%>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="email" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Email</label>
              <%= f.email_field :email, id: "user_email", class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "email" %>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="mobile-number" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Mobile No</label>
              <%= f.text_field :mobile_number, id: "mobile-number", class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Mobie" %>
            </div>
            <div class="col-span-1 md:col-span-2">
              <label for="address" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Address</label>
              <%= f.text_field :address, id: "address", class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Address" %>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="profession" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Profession</label>
              <%= f.text_field :profession, id: "profession", class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Profession"  %>
            </div>
            <div class="col-span-1 md:col-span-2">
              <div class="flex flex-wrap md:flex-nowrap lg:gap-6 md:gap-5">
                <div class="w-full md:w-[60%] lg-w-[70%]">
                  <label for="user_name" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Username</label>
                  <%= f.text_field :username, id:"user_name", class:" border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2 ", placeholder:"Username", autocomplete: "off" %>
                </div>
                <div class="w-full md:w-[40%] lg:w-[30%]">
                  <div class="pt-3 md:pt-7">
                    <span id="username_availability"></span>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="password" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Password</label>
              <%= f.password_field :password, id: "user_password" , class: " border border-gray-300 text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2", placeholder: "Password" %>
            </div>
            <div class="col-span-1 md:col-span-2 lg:col-span-1">
              <label for="gender" class="block mb-2 text-sm font-semibold text-[#555555] dark:text-white">Gender</label>
              <div class="flex" id="gender-radio-group">
                <div class="flex items-center mr-4">
                  <%= f.radio_button :gender, 'male', class:"w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500" %>
                  <label for="inline-radio" class="ml-2 text-sm font-semibold text-[#555555] dark:text-gray-300">Male</label>
                </div>
                <div class="flex items-center mr-4">
                  <%= f.radio_button :gender, 'female', class:"w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500" %>
                  <label for="inline-2-radio" class="ml-2 text-sm font-semibold text-[#555555] dark:text-gray-300">Female</label>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-span-1">
          <div class="pl-5 pt-4">
            <div id="previewSingle"></div>
            <div id="defaultUpload">
              <div class="w-[130px] h-[130px]"><img src="<%= asset_path('user.png') %>" alt="Image Description"  ></div>
            </div>
            <div class="file-input-wrapper mt-2">
              <label for="single_file" class=" px-10 py-1.5 bg-white text-[14px]   border-2 rounded-[4px] focus:border-[#66afe9] focus:ring-blue-200">
                <span class=" text-[#555555] font-thin ">Browse</span>
                <%= f.file_field :image, class: "hidden", id: "single_file", accept: "image/*" %>
              </label>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit "Add Teacher", class: 'ml-12 mb-8  md:ml-5 md:mb-5 text-white border border-[1px] border-[#2fa4e7] hover:border-[1px] hover:border-[#1684c2] bg-[#81B944] focus:ring-2 hover:ring-[#000] focus:outline-[#000] focus:ring-[#000] rounded-[4px] text-[14px] text-sm w-auto sm:w-auto px-3 py-2 text-center', style: 'background-image: linear-gradient(#54b4eb, #2fa4e7 60%, #1d9ce5);'%>
    <% end %>
  </div>
</div>