config/routes.rb
Rails.application.routes.draw do


  resources :academic_fees, except: %i[create new show destroy] do
    collection do
      get :find_academic_sections
      get :find_students
      get :find_student_details
      post :filter
      get :pay_fee
      get :changed_fee
    end
    member do
      post :create_payment
    end
  end

  resources :fee_dues, except: %i[create new edit update show destroy] do
    collection do
      get :find_academic_sections
      post :filter_fee_due
    end
  end

  resources :payments, except: %i[create new edit update show destroy]   do
    member do
      get :invoice
    end
  end


  namespace :staff do
    resources :notices, only: %i[index]
    resources :attendances, only: %i[index]
  end

  devise_for :users
  root 'home#index'

  resources :academic_details, except: %i[create new show]

  resources :schools, except: %i[index show destroy]

  resources :notices, except: %i[new show edit update]

  resources :students, except: %i[show] do
    collection do
      get :find_sections
      get :find_from_sections
      get :find_to_sections
      get 'promote'
      post 'update_sections'
    end
    member do
      patch :active_student
    end
  end

  namespace :parent do
    resources :attendance_views, only: %i[index]
    resources :notices, only: %i[index]
  end

  resources :user_attendances, except: %i[show edit update destroy create] do
    collection do
      post :update_all
    end
  end

  resources :student_attendances, except: %i[show new edit update destroy create] do
    collection do
      post :update_all
      get :attendance_view
    end
    collection do
      get :find_sections
    end
  end

  resources :standards, except: %i[show new] do
    resources :sections, only: []
  end

  namespace :admin do
    resources :admin_users, only: %i[edit update] do
    end
  end

  namespace :admin do
    resources :parent_users, except: [:show] do
      collection do
        get :check_username
      end
      member do
        patch :active_user
      end
    end
  end
  namespace :admin do
    resources :staff_users do
      member do
        patch :active_staff_user
      end
    end
  end
end

app/controllers/staff/attendance_views_controller.rb
# frozen_string_literal: true

# Staff::NoticesController is used to manage staff attendance.
class Staff::AttendanceViewsController < ApplicationController  # rubocop:disable Style/ClassAndModuleChildren
  def index
    @staff_id = current_user.id
    @selected_date = params[:selected_date]
    @attendances = Attendance.where(attendable_id: @staff_id, date: @selected_date)
    respond_to do |format|
      format.json { render json: @attendances }
      format.html { render :index }
    end
  end
end

app/controllers/staff/attendances_controller.rb
# frozen_string_literal: true

# Staff::NoticesController is used to manage staff attendance.
class Staff::AttendancesController < ApplicationController  # rubocop:disable Style/ClassAndModuleChildren
  def index
    @staff_id = current_user.id
    @selected_date = params[:selected_date]
    @attendances = Attendance.where(attendable_id: @staff_id, date: @selected_date)
    respond_to do |format|
      format.json { render json: @attendances }
      format.html { render :index }
    end
  end
end

app/controllers/staff/notices_controller.rb
# frozen_string_literal: true

# Parent::ParentNoticesController
class Staff::NoticesController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
  # GET /staff/staff_notices or /staff/staff_notices.json
  def index
    @staff_notices = Notice.where(notice_type: 'staff', notice_date: Date.today)
  end
end

app/controllers/staff/staff_attendance_views_controller.rb
# frozen_string_literal: true

# Parent::ParentNoticesController
class Staff::StaffAttendanceViewsController < ApplicationController  # rubocop:disable Style/ClassAndModuleChildren
  def index
    @staff_id = current_user.id
    @selected_date = params[:selected_date]
    @attendances = Attendance.where(attendable_id: @staff_id, date: @selected_date)
    respond_to do |format|
      format.json { render json: @attendances }
      format.html { render :index }
    end
  end
end

app/controllers/staff/staff_notices_controller.rb
# frozen_string_literal: true

# Parent::ParentNoticesController
class Staff::StaffNoticesController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
  # GET /staff/staff_notices or /staff/staff_notices.json
  def index
    @staff_notices = Notice.where(notice_type: 'staff', notice_date: Date.today)
  end
end

app/views/staff/staff_notices/index.html.erb
 <%= content_for :head do %>
  <%= javascript_import_module_tag "controllers/staff_notice_calendar" %>
<% end %>
<div class="bg-[#F5F5F5] mx-4 md:mt-[35px] text-[15px] lg:mt-0 mb-4 p-1 text-[#2FA4E7] pl-4"><span class="hover:text-[#157AB5]  hover:underline "><%= link_to "Home", root_path %></span><span class="mx-2 text-[#aba7a7]">/</span><span class="hover:text-[#157AB5]  hover:underline pointer" ><%= link_to "Noticeboard", staff_staff_notices_path %></span></div>
<div class="grid grid-cols-1 lg:grid-cols-2 gap-5 mx-4">
  <!-- teacher notice -->
  <div class="w-full">
    <div class="  mx-auto rounded-[5px] border-2">
      <div class=" px-5  flex items-center justify-between text-[#317EAC] shadow-2xl" style="background: linear-gradient(rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0.1) 100%);">
        <div><i class="fa-solid fa-pen-to-square"></i>
          <span class="font-semibold text-[15px]">Staff Noticeboard</span></div>
        <button id="updown" class="accordian-header cursor-pointer duration-700 text-2xl leading-0 px-1 my-1  border bg-white text-black font-extrabold h-[26px] rounded-[12px]"> <i class="bx bx-chevron-up"></i></button>
      </div>
      <div class="accordian-body p-2 relative ">
        <span class="text-[15px] text-[#555555] font-extrabold "> Date:  </span><span class="text-[#555555] text-[15px]"><%= Date.today %></span>
        <hr class="my-4">
        <div class="text-[#555555] font-light text-[14px] my-10">
          <% if @staff_notices.empty? %>
            <p class="text-[#555555] font-light text-[14px] my-10">No Notice Found</p>
          <% else %>
            <% @staff_notices.each do |notice| %>
              <div class="flex flex-col">
                <div >
                  <p >
                    <%= notice.notice %>
                  </p>
                </div>
                <div class="self-end absolute bottom-0 flex gap-2">
                  <div>
                    <%= notice.updated_at.in_time_zone('Asia/Kolkata').strftime("%I:%M %p") %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="w-full">
    <div class="  mx-auto rounded-[5px] border-2">
      <div class=" px-5  flex items-center justify-between text-[#317EAC] shadow-2xl" style="background: linear-gradient(rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0.1) 100%);">
        <div><i class="fa-solid fa-pen-to-square"></i>
          <span class="font-semibold text-[15px]">calendar</span></div>
        <button id="updown" class="accordian-header cursor-pointer duration-700 text-2xl leading-0 px-1 my-1  border bg-white text-black font-extrabold h-[26px] rounded-[12px]"> <i class="bx bx-chevron-up"></i></button>
      </div>
      <div class="accordian-body w-full">
        <div class="w-full mt-2">
          <div id='staff-notice-calendar' class="w-full p-2 "></div>
        </div>
      </div>
    </div>
  </div>
</div>