config/routes.rb
Rails.application.routes.draw do


  resources :academic_fees, except: %i[create new show destroy] do
    collection do
      get :find_academic_sections
      get :find_students
      get :find_student_details
      post :filter
      get :pay_fee
      get :changed_fee
    end
    member do
      post :create_payment
    end
  end

  resources :fee_dues, except: %i[create new edit update show destroy] do
    collection do
      get :find_academic_sections
      post :filter_fee_due
    end
  end

  resources :payments, except: %i[create new edit update show destroy]   do
    member do
      get :invoice
    end
  end


  namespace :staff do
    resources :notices, only: %i[index]
    resources :attendances, only: %i[index]
  end

  devise_for :users
  root 'home#index'

  resources :academic_details, except: %i[create new show]

  resources :schools, except: %i[index show destroy]

  resources :notices, except: %i[new show edit update]

  resources :students, except: %i[show] do
    collection do
      get :find_sections
      get :find_from_sections
      get :find_to_sections
      get 'promote'
      post 'update_sections'
    end
    member do
      patch :active_student
    end
  end

  namespace :parent do
    resources :attendance_views, only: %i[index]
    resources :notices, only: %i[index]
  end

  resources :user_attendances, except: %i[show edit update destroy create] do
    collection do
      post :update_all
    end
  end

  resources :student_attendances, except: %i[show new edit update destroy create] do
    collection do
      post :update_all
      get :attendance_view
    end
    collection do
      get :find_sections
    end
  end

  resources :standards, except: %i[show new] do
    resources :sections, only: []
  end

  namespace :admin do
    resources :admin_users, only: %i[edit update] do
    end
  end

  namespace :admin do
    resources :parent_users, except: [:show] do
      collection do
        get :check_username
      end
      member do
        patch :active_user
      end
    end
  end
  namespace :admin do
    resources :staff_users do
      member do
        patch :active_staff_user
      end
    end
  end
end

app/controllers/parent/attendance_views_controller.rb
# frozen_string_literal: true

# Parent::ParentNoticesController
class Parent::AttendanceViewsController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
  include AuthorizationParentHelper
  # GET /parent/parent_attendance_views or /parent/parent_attendance_views.json
  def index
    @student_id = params[:student_id]
    @selected_date = params[:selected_date]
    @attendances = Attendance.where(attendable_id: @student_id, date: @selected_date)
    respond_to do |format|
      format.json { render json: @attendances }
      format.html { render :index }
    end
  end
end

app/controllers/parent/notices_controller.rb
# frozen_string_literal: true

# Parent::ParentNoticesController
class Parent::NoticesController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
  include AuthorizationParentHelper
  before_action :check_user_role
  # GET /parent/notices or /parent/notices.json
  def index
    @parent_notices = Notice.where(notice_type: 'parent', notice_date: Date.today)
  end
end

app/controllers/parent/parent_attendance_views_controller.rb
# frozen_string_literal: true

# Parent::ParentNoticesController
class Parent::ParentAttendanceViewsController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
  include AuthorizationParentHelper
  before_action :check_user_role
  # GET /parent/parent_attendance_views or /parent/parent_attendance_views.json
  def index
    @student = params[:student_id]
    @selected_date = params[:selected_date]
    @attendances = Attendance.where(attendable_id: @student, date: @selected_date)
    respond_to do |format|
      format.json { render json: @attendances }
      format.html { render :index }
    end
  end
end

app/controllers/parent/parent_notices_controller.rb
# frozen_string_literal: true

# Parent::ParentNoticesController
class Parent::ParentNoticesController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
  include AuthorizationParentHelper
  before_action :check_user_role
  # GET /parent/notices or /parent/notices.json
  def index
    @parent_notices = Notice.where(notice_type: 'parent', notice_date: Date.today)
  end
end

app/views/parent/parent_attendance_views/index.html.erb
 <%= content_for :head do %>
  <%= javascript_import_module_tag "controllers/attendance_calendar" %>
<% end %>
<div class="bg-[#F5F5F5] mx-4 md:mt-[35px] text-[15px] lg:mt-0 mb-4 p-1 text-[#2FA4E7] pl-4"><span class="hover:text-[#157AB5]  hover:underline "><%= link_to "Home", root_path %></span><span class="mx-2 text-[#aba7a7]">/</span><span class="hover:text-[#157AB5]  hover:underline pointer" ><%= link_to "Sudent Attendance", parent_parent_attendance_views_path %></span></div>
<div class=" container mx-auto rounded-[5px] border-2 relative">
  <div class=" px-5  flex items-center justify-between text-[#317EAC] shadow-2xl", style="background: linear-gradient(to bottom, rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0.1) 100%);">
    <div><i class="fa-solid fa-pen-to-square"></i>
      <span class="font-semibold text-[15px]">Student Attendance</span></div>
    <button id="updown" class="accordian-header cursor-pointer duration-700 text-2xl leading-0 px-1 my-1  border bg-white text-black font-extrabold h-[26px] rounded-[12px]"> <i class="bx bx-chevron-up"></i></button>
  </div>
  <div class="accordian-body bg-[#ffffff] ">
    <div class="p-3 ">
      <div class="w-full container hidden  text-[#B94A48] mx-auto conatiner mb-3  text-[14px] p-4 rounded bg-[#F2DEDE] " id="error-div">
        <ul>
          <li class="error" id="student-error"></li>
          <li class="error" id="date-error"></li>
        </ul>
      </div>
      <div class='p-3 w-full flex flex-col'>
        <div class="flex flex-col md:flex-row gap-2 md:items-center w-full gap-x-4">
          <div class=" w-full md:w-[75%]">
            <%= form_tag parent_parent_attendance_views_path, method: :get do  %>
              <div class= 'flex flex-col md:flex-row gap-2 md:items-center w-full gap-x-6'>
                <div class="w-full md:w-[25%]">
                  <%= label_tag :student, "Student", class: 'text-[15px] text-[#555555] font-semibold' %>
                  <%= select_tag :student_id, options_from_collection_for_select(Student.where(user_id: current_user.id), 'id', 'name', params[:student_id]), prompt: 'Select a Student', class: "border border-gray-300  text-gray-900 text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2.0 standard" %>
                </div>
                <div class="w-full md:w-[25%]">
                  <%= label_tag :date, "Date" , class: 'text-[15px] text-[#555555] font-semibold' %>
                  <%= date_field_tag :date, params[:date],  class: " border border-gray-300 bg-[#EEEEEE] text-gray-900 text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2.0", id: 'date' %>
                </div>
                <div class="md:mt-[20px]">
                  <%= submit_tag "View", id: 'date_submit' ,class:'text-white bg-[#81B944] getAttendanceData   focus:ring-2 hover:ring-[#000] focus:outline-[#000] focus:ring-[#000] font-semibold rounded-[5px] text-sm  w-auto sm:w-auto px-4  py-2 text-center'%>
                </div>
              </div>
            <% end %>
          </div>
          <div class="w-[30%] md:w-[15%] flex flex-row gap-3 md:flex md:flex-col md:gap-0">
            <div class="p-1 bg-[#008000] text-white font-semibold mb-1 "> Present </div>
            <div class="p-1 bg-[indigo] text-white font-semibold mb-1 ">Late </div>
            <div class="p-1 bg-[#FF0000] text-white font-semibold mb-1 ">Absent </div>
          </div>
        </div>
        <div class="w-full mt-2">
          <div id='calendar' class="w-full p-2 "></div>
        </div>
      </div>
    </div>
  </div>
</div>