config/routes.rb
Rails.application.routes.draw do


  resources :academic_fees, except: %i[create new show destroy] do
    collection do
      get :find_academic_sections
      get :find_students
      get :find_student_details
      post :filter
      get :pay_fee
      get :changed_fee
    end
    member do
      post :create_payment
    end
  end

  resources :fee_dues, except: %i[create new edit update show destroy] do
    collection do
      get :find_academic_sections
      post :filter_fee_due
    end
  end

  resources :payments, except: %i[create new edit update show destroy]   do
    member do
      get :invoice
    end
  end


  namespace :staff do
    resources :notices, only: %i[index]
    resources :attendances, only: %i[index]
  end

  devise_for :users
  root 'home#index'

  resources :academic_details, except: %i[create new show]

  resources :schools, except: %i[index show destroy]

  resources :notices, except: %i[new show edit update]

  resources :students, except: %i[show] do
    collection do
      get :find_sections
      get :find_from_sections
      get :find_to_sections
      get 'promote'
      post 'update_sections'
    end
    member do
      patch :active_student
    end
  end

  namespace :parent do
    resources :attendance_views, only: %i[index]
    resources :notices, only: %i[index]
  end

  resources :user_attendances, except: %i[show edit update destroy create] do
    collection do
      post :update_all
    end
  end

  resources :student_attendances, except: %i[show new edit update destroy create] do
    collection do
      post :update_all
      get :attendance_view
    end
    collection do
      get :find_sections
    end
  end

  resources :standards, except: %i[show new] do
    resources :sections, only: []
  end

  namespace :admin do
    resources :admin_users, only: %i[edit update] do
    end
  end

  namespace :admin do
    resources :parent_users, except: [:show] do
      collection do
        get :check_username
      end
      member do
        patch :active_user
      end
    end
  end
  namespace :admin do
    resources :staff_users do
      member do
        patch :active_staff_user
      end
    end
  end
end

app/controllers/student_attendances_controller.rb
# frozen_string_literal: true

# this is a controller for student attendance page
class StudentAttendancesController < ApplicationController
  before_action :check_role
  def find_sections
    @sections = Standard.find_by(id: params[:standard_id]).sections
    respond_to(&:js)
  end

  def update_all
    attendances_params = params.require(:attendances).permit!

    attendances_params.each do |_student_id, attendance_params|
      update_or_create_attendance(attendance_params)
    end

    redirect_to student_attendances_path
  end

  def index
    @selected_date = params[:date]
    @selected_standard = params[:standard_id]
    @selected_section = params[:section_id]
    @students = Student.active.where(section_id: @selected_section)
  end

  def attendance_view
  end

  private

  def check_role
    return if current_user && (current_user.role == 'admin' || current_user.role == 'staff')

    flash[:alert] = 'You do not have permission to access this page.'
    redirect_to root_path
  end

  def update_or_create_attendance(attendance_params)
    student_id = attendance_params[:attendable_id]
    date = attendance_params[:date]

    student = Student.find(student_id)
    attendance = Attendance.find_or_initialize_by(attendable_id: student_id, attendable_type: student.class.name,
                                                  date:)

    attendance.update(attendance_params)
    attendance.set_color(current_user.id)
    attendance.save
  end
end

app/helpers/student_attendances_helper.rb
module StudentAttendancesHelper
end

app/views/student_attendances/_section_dropdown.html.erb
<div class="w-full">
  <label for="section" class='text-[15px] text-[#555555] font-semibold'>Section</label>
  <select id="section_id" name="[section_id]" class= "border border-[#dddddd] text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2.0 ">
    <option value="">Select Section</option>
    <% sections.each do |section| %>
      <option value="<%= section.id %>"><%= section.section_name %></option>
    <% end %>
  </select>
</div>

app/views/student_attendances/find_sections.js.erb
$('#section-dropdown').html('<%= j render partial: "section_dropdown", locals: { sections: @sections } %>');

app/views/student_attendances/get_sections.js.erb
$('#section-dropdown').html('<%= j render partial: "section_dropdown", locals: { sections: @sections } %>');

app/views/student_attendances/index.html.erb
 <%= content_for :head do %>
  <%= javascript_import_module_tag "controllers/student_attendance" %>
<% end %>
<div class=" bg-[#F5F5F5] p-1.5 text-[14px] pl-4 mx-3 mb-8 text-[#2FA4E7] "><span class="hover:text-[#157AB5]  hover:underline "><%=link_to "Home", root_path %></span><span class="mx-2 text-[#aba7a7]">/</span><span class="hover:text-[#157AB5]  hover:underline "><%= link_to "Students Attendance", student_attendances_path %></span></div>
<div class="mx-2 md:mx-4 rounded-[5px] border-2 relative">
  <div class="px-5 bg-[#EDEDED] flex items-center justify-between text-[#317EAC] shadow-2xl", style="background: linear-gradient(rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0.1) 100%);">
    <div><i class="fa-solid fa-pen-to-square"></i>
      <span class="font-semibold text-[15px]">Student Attendance</span></div>
    <button id="updown" class="accordian-header cursor-pointer duration-700 text-2xl leading-0 px-1 my-1  border bg-white text-black font-extrabold h-[26px] rounded-[12px]"> <i class="bx bx-chevron-up"></i></button>
  </div>
  <div class="accordian-body bg-[#ffffff] min-h-[450px]">
    <div class="py-0 px-3 ">
      <div class="w-full container hidden error-div text-[#a94442] mx-auto conatiner my-2  text-[14px] p-4 rounded bg-[#F2DEDE] ">
        <ul>
          <li class="error" id="standard-error"></li>
          <li class="error" id="section-error"></li>
          <li class="error" id="date-error"></li>
        </ul>
      </div>
      <div class='py-2 px-1 md:px-3 w-full'>
        <%= form_tag student_attendances_path, method: :get do  %>
          <div class= 'flex flex-col md:flex-row gap-2 md:items-center w-full gap-x-6'>
            <div class="w-full md:w-[25%]">
              <%= label_tag :standard, "Standard", class: 'text-[14px] text-[#555555] font-semibold' %>
              <%= select_tag :standard_id, options_from_collection_for_select(Standard.where(removed: false), 'id', 'name', params[:standard_id]), prompt: 'Select a Standard', class: "border border-[#dddddd] text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2.0 standard" %>
            </div>
            <div class="w-full md:w-[25%]" id="section-dropdown">
              <%= label_tag :section, "Section", class: 'text-[14px] text-[#555555] font-semibold' %>
              <%= select_tag :section_id, options_from_collection_for_select( Section.where(standard_id: params[:standard_id]), 'id', 'section_name', params[:section_id]), prompt: 'Select a Section', class: "border border-[#dddddd] text-[#555555] text-sm rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2.0 " %>
            </div>
            <div class="w-full md:w-[25%]">
              <%= label_tag :date, "Date" , class: 'text-[14px] text-[#555555] font-semibold' %>
              <%= date_field_tag :date, params[:date],  class: " border border-[#dddddd] bg-[#EEEEEE] text-[#555555] text-[14px] rounded-[5px] focus:border-[#66afe9] focus:ring-blue-200 block w-full p-2.0", id: 'date' %>
            </div>
            <div class="md:mt-[20px]">
              <%= submit_tag "View", id: 'date_submit', class: 'border border-[1px] border-transparent hover:border-[1px] hover:border-[#547a29] text-white bg-[#81B944] text-[14px] focus:ring-2 hover:ring-[#000] focus:outline-[#000] focus:ring-[#000]  rounded-[5px] text-sm w-auto sm:w-auto px-4 py-2 text-center', style: 'background-image: linear-gradient(#88c149, #73a839 60%, #699934);' %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="w-full mb-8 text-[14px] <%= "hidden" unless @students.present? %>" id="table-div">
        <%= form_tag update_all_student_attendances_path, method: :post do %>
          <div class="overflow-x-auto w-full">
            <table class="table table-striped w-full border-collapse border border-[#dddddd] ">
              <thead class="text-[14px] text-[#555555] font-semibold text-left">
                <tr>
                  <th class="border border-[#dddddd] p-2">Student</th>
                  <th class="border border-[#dddddd] p-2">Roll No</th>
                  <th class="border border-[#dddddd] p-2">Status</th>
                </tr>
              </thead>
              <tbody>
                <% @students.each do |student| %>
                  <tr class='striped'>
                    <td class="border border-[#dddddd] p-2 text-[#2fa4e7] font-light">
                      <%= link_to student.name, parent_attendance_views_path(student_id: student.id, date: @selected_date) %>
                    </td>
                    
                    <td class="border border-[#dddddd] p-2 text-[#555555] font-light "><%= student.roll_no %></td>
                    <td class="border border-[#dddddd] p-2 text-[#555555] font-semibold">
                      <%= hidden_field_tag "attendances[#{student.id}][attendable_id]", student.id %>
                      <%= hidden_field_tag "attendances[#{student.id}][attendable_type]", student.class.name %>
                      <%= hidden_field_tag "attendances[#{student.id}][date]", @selected_date %>
                      <% attendance = Attendance.find_by(attendable_id: student.id, attendable_type: student.class.name, date: @selected_date) %>
                      <div class="flex items-center gap-1 text-[14px]">
                        <%= radio_button_tag "attendances[#{student.id}][status]", "present", checked: attendance&.status == "present" %> <span class="mr-3">Present</span>
                        <%= radio_button_tag "attendances[#{student.id}][status]", "late", checked: attendance&.status == "late" %> <span class="mr-3">Late</span>
                        <%= radio_button_tag "attendances[#{student.id}][status]", "absent", checked: attendance&.status == "absent" %> Absent
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="flex justify-center mt-12  md:bottom-[-20px] md:left-[50%] md:right-[50%]">
            <%= submit_tag "Submit Attendance",class:'text-white bg-[#033c73]    focus:ring-2 hover:ring-[#000] focus:outline-[#000] focus:ring-[#000]  rounded-[5px] text-sm  w-auto sm:w-auto px-4  py-2 text-center' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>